### ISSUE TITLE
Add `copy` and `move` to the list of features

### ISSUE THREAD

**Issue by GabeDuarteM** [PhilRunninger/nerdtree-visual-selection#5]
Hey 👋👋👋

It would be good to have also the possibility to move and copy multiple nodes into a new location, that way, we would be able to do most of the important operations that you could do with multiple items (at the moment, you can only open and delete them)

What do you think?

**Comment by PhilRunninger** [comment]
I like the idea. Here are my initial thoughts.

1. Since we are dealing with multiple items, the destination should be just a single directory.
1. Each file or folder moved/copied should be confirmed. That way you can, for example, select 5 consecutive nodes and copy all but the 3rd.
1. Add a way to pre-select the destination folder, or at least most of it.

Here is an example of how I see all of this playing out.
1. Navigate to destination folder.
1. `D` This is the plugin's keystroke for marking the **D**estination. I plan no visual indicator for this.
1. `V5j` (Navigate to and) select six source file/folders.
1. `m` Move files/folders.
1. Plugin presents a prompt with pre-selected destination folder (or if a file was pre-selected, its path). This allows the user to add subfolders if necessary. If the destination wasn't preselected, show the folder of the first node.
1. `Enter` Start moving the files.
1. Answer the `[Y]es, (N)o, (A)ll, (C)ancel:` prompt for each file/folder.

**Comment by GabeDuarteM** [comment]
1. Yeah, sounds reasonable
2. Initially, I thought about only one confirmation, but this use case sounds reasonable too, especially when we have an `(A)ll` option...
3. My initial idea was to just follow what NERDTree is doing today when you move/copy a single item, showing you an `Enter the new path for the node:`, passing the parent of the selected files as the default, and letting you use the autocomplete to select the final destination (automatically creating the parts that do not exist, if you want to move to a new inexistent folder). I think the `D` mapping could be useful when you want to move the file to somewhere far from where it currently is, but when it's close, I think nerdtree's behavior is probably faster than preselecting with `D`, so I think it would be nice to have both behaviors available, so on step 5 of your example, you would have the option to change the default path (which is either the folder of the first node, or the selected folder with the `D` map), and allowing to use autocomplete, as it currently happens with nerdtree

![image](https://user-images.githubusercontent.com/7675500/65154692-3f7bb980-da2c-11e9-8d1d-b1e628776be2.png)

**Comment by Nnoerregaard** [comment]
Any progress on this issue? I would love the ability to move and copy multiple files at a time in NerdTREE

**Comment by PhilRunninger** [comment]
Not yet. I haven't had the time to look into it.
